#!/usr/bin/env python3
"""
build.py — Redpanda Lovelace Cards bundle builder
No dependencies beyond the Python standard library.

Usage:
    python3 build.py

Reads every .js file listed in CARD_FILES from src/ and concatenates them
into dist/redpanda-lovelace-cards.js. Edit cards individually in src/,
then run this script and commit both src/ and dist/.
"""

import os
import re
import sys
from pathlib import Path

# ── Configuration ─────────────────────────────────────────────────────────────

VERSION_FILE = Path(__file__).parent / "version.txt"

# Order matters — determines load order in the bundle.
# Add new card filenames here when you add cards to src/.
CARD_FILES = [
    "petlibro-fountain-card.js",
    "petlibro-feeder-card.js",
    "levoit-vital200s-card.js",
    "lg-washer-dryer-card.js",
]

SRC_DIR  = Path(__file__).parent / "src"
DIST_DIR = Path(__file__).parent / "dist"
OUT_FILE = DIST_DIR / "ha-cards.js"

# ── Helpers ───────────────────────────────────────────────────────────────────

def read_version() -> str:
    if VERSION_FILE.exists():
        return VERSION_FILE.read_text().strip()
    return "unknown"

# ── Build ─────────────────────────────────────────────────────────────────────

def build():
    version = read_version()
    DIST_DIR.mkdir(exist_ok=True)

    card_list = "\n".join(f" *   - {f}" for f in CARD_FILES)
    banner = f"""\
/**
 * Redpanda Lovelace Cards — v{version}
 * Bundled from individual card files in src/
 * DO NOT EDIT THIS FILE DIRECTLY — edit the files in src/ and run: python3 build.py
 *
 * Cards included:
{card_list}
 */

"""
    chunks = [banner]
    built = []
    skipped = []

    for filename in CARD_FILES:
        src_path = SRC_DIR / filename
        if not src_path.exists():
            print(f"  WARNING: {filename} not found in src/ — skipping")
            skipped.append(filename)
            continue

        content = src_path.read_text(encoding="utf-8").rstrip()
        sep = "─" * 72
        chunks.append(f"\n/* {sep} */\n")
        chunks.append(f"/* {filename:<70} */\n")
        chunks.append(f"/* {sep} */\n\n")
        chunks.append(content)
        chunks.append("\n")
        built.append(filename)

    OUT_FILE.write_text("".join(chunks), encoding="utf-8")

    size_kb = OUT_FILE.stat().st_size / 1024
    print(f"✓  Built {OUT_FILE.relative_to(Path(__file__).parent)}  ({size_kb:.1f} KB)  v{version}")
    print(f"   Cards bundled : {len(built)}")
    if skipped:
        print(f"   Skipped       : {', '.join(skipped)}")
    if skipped:
        sys.exit(1)

if __name__ == "__main__":
    build()
