#!/usr/bin/env node
/**
 * build.js — concatenates all src/*.js card files into dist/redpanda-lovelace-cards.js
 *
 * Usage:  node build.js
 *
 * Each card in src/ stays fully independent — edit them individually.
 * The dist/ bundle is what HACS serves to Home Assistant.
 * Run this script and commit both src/ and dist/ to the repo.
 * When you release a new version, bump the version in package.json,
 * run `node build.js`, commit, and create a GitHub release.
 */

const fs   = require('fs');
const path = require('path');

const srcDir  = path.join(__dirname, 'src');
const distDir = path.join(__dirname, 'dist');
const outFile = path.join(distDir, 'redpanda-lovelace-cards.js');

const pkg     = JSON.parse(fs.readFileSync(path.join(__dirname, 'package.json'), 'utf8'));
const version = pkg.version;

// Ordered list — determines load order in the bundle
const CARD_FILES = [
  'petlibro-fountain-card.js',
  'petlibro-feeder-card.js',
  'levoit-vital200s-card.js',
  'lg-washer-dryer-card.js',
];

if (!fs.existsSync(distDir)) fs.mkdirSync(distDir);

const banner = `/**
 * Redpanda Lovelace Cards — v${version}
 * Bundled from individual card files in src/
 * DO NOT EDIT THIS FILE DIRECTLY — edit the files in src/ and run: node build.js
 *
 * Cards included:
${CARD_FILES.map(f => ` *   - ${f}`).join('\n')}
 */\n\n`;

let bundle = banner;

for (const file of CARD_FILES) {
  const srcPath = path.join(srcDir, file);
  if (!fs.existsSync(srcPath)) {
    console.warn(`WARNING: ${file} not found in src/, skipping.`);
    continue;
  }
  const content = fs.readFileSync(srcPath, 'utf8');
  bundle += `\n/* ${'─'.repeat(72)} */\n`;
  bundle += `/* ${file.padEnd(70)} */\n`;
  bundle += `/* ${'─'.repeat(72)} */\n\n`;
  bundle += content.trimEnd();
  bundle += '\n';
}

fs.writeFileSync(outFile, bundle, 'utf8');

const kb = (fs.statSync(outFile).size / 1024).toFixed(1);
console.log(`✓ Built dist/redpanda-lovelace-cards.js  (${kb} KB)  v${version}`);
console.log(`  Cards: ${CARD_FILES.length}`);
